import Head from "next/head";
import { Inter } from "@next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "@/Component/Header/Header";
import UpperSide from "@/Component/UpperSide/UpperSide";
import Middle from "@/Component/Middle/Middle";
import MiddleLast from "@/Component/MiddleLast/MiddleLast";
import LastSide from "@/Component/LastSide/LastSide";
import LastPage from "@/Component/Last/LastPage";
import LastPage2 from "@/Component/LastPage2/LastPage2";
import Table from "@/Component/Table/Table";
import Testimonial from "@/Component/Testimonial/Testimonial";
import Footer from "@/Component/Footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Gym App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <Header></Header>
      <UpperSide></UpperSide>
      <Middle></Middle>
      <MiddleLast></MiddleLast>
      <LastSide></LastSide>
      <LastPage></LastPage>
      <LastPage2></LastPage2>
      <Table></Table>
      <Testimonial></Testimonial>
      <Footer></Footer>
    </>
  );
}
